### PR TITLE
Add :match() selector

### PR DESCRIPTION
**Pull request by reedstrm**
This  matches based on regex against text content of subtree. Has an ElementTree agnostic subtree textmethod. Tested against xml.etree.ElementTree, xml.etree.cElementTree, and lxml.etree

### CODE REVIEW

**Comment by mmulich** [comment]
You should probably squash the commit for the travis filename change into the parent commit.

**Comment by mmulich** [comment]
It's probably better to use travis' native version matrix. This will startup the machine faster and when you look at the output you'll know immediately if one version over another is failing because each version is done as it's own run. See also [cnx-epub's .travis.yml](https://github.com/Connexions/cnx-epub/blob/9a65856dc3259a5c9e5f9c04fbc7868681a6e1ff/.travis.yml)

This would be the relevant bit to add to the configuration:

``` yml
python:
  - "2.7"
  - "3.4"
```

And then you'd call `pytest ...` or `setup.py test` or similar for the execution of the tests.

**Comment by reedstrm** [comment]
@pumazi Should I make any effort to be 3.2 compatible, or just skip that one? apparently, strval = u'' was invalid for that one subversion ...

**Comment by karenc** [comment]
I think 3.2 is a pain... so let's not support that :p

**Comment by mmulich** [comment]
IMO targeting 3.x >= 3.3 and now I just think targeting 3.4 is sufficient.

**Comment by reedstrm** [comment]
Since this is intended as a general use library, I'll leave in all versions that pass. :-)

**Comment by reedstrm** [comment]
Easybake merge is waiting on this.

**Pull request merged**
